//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class user
    {
        public int UserId { get; set; }

        [Required(ErrorMessage = "Email Address is required")]
        [DataType(DataType.EmailAddress, ErrorMessage = "This must be a valid email address")]
        public string Email { get; set; }
        
        [Required]
        [MinLength(6, ErrorMessage = "Minimum length should be greater than 6")]
        public string Password { get; set; }
        public string PasswordSalt { get; set; }

        [Required(ErrorMessage = "This field cannot be left blanked")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        [Required(ErrorMessage = "This field cannot be left blanked")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        
        public string UserType { get; set; }
    }
}
